services:
  minecraft-1.20.4:
    image: itzg/minecraft-server
    tty: true
    ports:
      - 25565:25565
    environment:
      - TYPE=PAPER
      - EULA=TRUE
      - VERSION=1.20.4
    volumes:
      - ./data:/data
