services:
  minecraft-1.18.2:
    image: itzg/minecraft-server
    tty: true
    ports:
      - 25565:25565
    environment:
      - TYPE=SPIGOT
      - EULA=TRUE
      - VERSION=1.18.2
    volumes:
      - ./data:/data
